:global:
  build:
    matrix:
      - GOOS: linux
        GOARCH: amd64
      - GOOS: darwin
        GOARCH: amd64
.travis.yml:
  sudo: true
  dist: trusty
  before_install:
    - wget https://apt.puppetlabs.com/puppetlabs-release-pc1-wheezy.deb && sudo dpkg -i puppetlabs-release-pc1-wheezy.deb
    - sudo apt-get update && sudo apt-get install -y puppet-agent
    - sudo ln -s /opt/puppetlabs/bin/facter /usr/local/bin/facter
    - facter
  env:
    global:
      - ORG_PATH=/home/travis/gopath/src/github.com/intelsdi-x
      - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}
    matrix:
      - TEST_TYPE=small
      - TEST_TYPE=medium
